export { AgentRelayClient, registerAgent } from "./client.js";
export { RelayError, RelayAuthError, RelayConnectionError } from "./errors.js";
export type {
  RelayClientConfig,
  AgentProfile,
  UpdateProfileInput,
  HeartbeatResult,
  RegisterInput,
  RegisterResult,
  Project,
  CreateProjectInput,
  Channel,
  CreateChannelInput,
  Message,
  SendMessageInput,
  GetMessagesOptions,
  Snapshot,
  CreateSnapshotInput,
  Invite,
  CreateInviteInput,
  OllamaChatInput,
  OllamaChatResponse,
  OllamaGenerateInput,
  OllamaGenerateResponse,
  OllamaEmbedInput,
  OllamaEmbedResponse,
  OllamaModel,
  OllamaModelsResponse,
  ApiResponse,
  ApiError,
} from "./types.js";
